services:
  bacdz:
    build: .
    container_name: bac-dz-pro
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - bacdz_data:/app/data

volumes:
  bacdz_data:
